### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by uraway** [uraway/SimpleRiddles#1]
- [ ] add README.md file
- [ ] create RiddlesList, Home page where describes the abstract of the application
- [ ] design improve
- [ ] add more riddles!!
